'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
type Agent={id:string;name:string;role:string;bio:string;photoUrl:string;phone:string;email:string;whatsapp:string;licenseVerified:boolean;identityVerified:boolean;backgroundCheckVerified:boolean};
export default function AgentDirectory({agents}:{agents:Agent[]}){
 const [q,setQ]=useState(''); const [role,setRole]=useState('All');
 const roles=useMemo(()=>['All',...Array.from(new Set(agents.map(a=>a.role).filter(Boolean)))],[agents]);
 const filtered=useMemo(()=>agents.filter(a=>(role==='All'||a.role===role)&&(`${a.name} ${a.role} ${a.bio}`.toLowerCase().includes(q.toLowerCase()))),[agents,q,role]);
 return <><div className="agent-tools"><div className="agent-search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search agents by name, role or expertise" aria-label="Search agents"/></div><select value={role} onChange={e=>setRole(e.target.value)} aria-label="Filter by role">{roles.map(r=><option key={r}>{r}</option>)}</select></div><div className="agent-resultbar"><span>{filtered.length} verified {filtered.length===1?'professional':'professionals'}</span><span>Identity • License • Contact • Compliance</span></div>{filtered.length===0?<div className="empty panel">No verified agents match your search.</div>:<div className="agentgrid">{filtered.map(a=><article className="agentcard" key={a.id}><div className="agentphoto">{a.photoUrl?<img src={a.photoUrl} alt={a.name}/>:<span>{a.name.slice(0,1)}</span>}<span className="agentverifiedpill">✓ Verified</span></div><div className="agentbody"><div className="verified">ELDERZ VERIFIED PROFESSIONAL</div><h3>{a.name}</h3><p className="muted">{a.role}</p><p>{a.bio}</p><div className="chips"><span className="chip">Identity</span>{a.licenseVerified&&<span className="chip">License</span>}{a.backgroundCheckVerified&&<span className="chip">Background</span>}</div><div className="agentcontact"><Link href={`/agents/${a.id}`} className="agent-view">View profile</Link>{a.phone&&<a href={`tel:${a.phone}`}>Call</a>}{a.whatsapp&&<a href={`https://wa.me/${a.whatsapp.replace(/\D/g,'')}`}>WhatsApp</a>}</div></div></article>)}</div>}</>
}
