import Link from 'next/link';
import {db} from '@/lib/prisma';
import AgentDirectory from '@/components/AgentDirectory';
export const dynamic='force-dynamic';
export default async function Agents(){
 const agents=await db.agent.findMany({where:{status:'VERIFIED'},orderBy:{createdAt:'desc'}});
 return <main><section className="section cream"><div className="container agenthero"><div><div className="eyebrow blue">Elderz professional network</div><h1>Find a property professional you can trust.</h1><p className="lead">Browse verified Elderz agents, review their professional information and contact them directly for property sales, rentals and advisory support.</p><div className="agent-hero-actions"><Link className="btn-primary" href="/agents/apply">Become an agent</Link><Link className="btn secondary" href="/properties">Browse properties</Link></div></div><div className="agenttrust"><strong>Verification-first network</strong><span>Identity • Contact • License • Supporting documents • Review</span><b>{agents.length} verified</b></div></div></section>
 <section className="section"><div className="container"><div className="sectionhead"><div><div className="eyebrow">Our professionals</div><h2>Meet the Elderz agent network.</h2><p>Search by name, role or expertise.</p></div><Link className="text-link" href="/agents/apply">Join the network →</Link></div><AgentDirectory agents={agents}/></div></section>
 <section className="agent-services"><div className="container"><div><div className="eyebrow blue">What agents can help with</div><h2>One network. Multiple property needs.</h2></div><div className="service-tiles"><div><strong>Property sales</strong><span>Buyer guidance, viewings and enquiries.</span></div><div><strong>Rentals & letting</strong><span>Find suitable homes and coordinate next steps.</span></div><div><strong>Land & investment</strong><span>Explore land opportunities and investment enquiries.</span></div><div><strong>Professional support</strong><span>Connect with a verified person from first enquiry to follow-up.</span></div></div></div></section></main>
}
